version: "3"

services:

  kafkamanager:
    image: fgr206/kafkamanager
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      ZK_HOSTS: 'localhost:62181'

  km-zookeeper:
    image: 'zookeeper'
    #network_mode: "service:kafkamanager"
    ports:
      - "62181:2181"
    networks:
      - kafkamanager-net
    volumes:
      - ~/fgr_dockervolumes/kafkamanager_conf/data:/data
      - ~/fgr_dockervolumes/kafkamanager_conf/datalog:/datalog
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

networks:
  kafkamanager-net: